import type { SupplierDetail } from "../_types"

export const supplierDetailMockData: Record<string, SupplierDetail> = {
  "1": {
    id: "1",
    name: "Ekspress24 Kargo",
    supplierType: "ozmal",
    status: "active",
    contractType: "fixed_salary",
    contactPerson: "Ahmet Yılmaz",
    contactPersonTitle: "Operasyon Direktörü",
    contactPhone: "+90 212 555 0001",
    contactEmail: "ahmet.yilmaz@ekspress24.com",
    city: "İstanbul",
    vehicleCount: 12,
    driverCount: 15,
    activeTripsCount: 4,
    totalTripsCount: 1842,
    isDeletable: false,
    isDeactivatable: false,
    hasExpiringDocuments: false,
    createdAt: "2020-01-01",
    updatedAt: "2024-01-15",
    createdBy: "Sistem",
    // Yasal
    taxOffice: "Kadıköy V.D.",
    taxNumber: "1234567890",
    officialAddress: "Atatürk Cad. No:1 Kadıköy / İstanbul",
    // Banka
    iban: "TR12 0001 0017 0000 0001 2345 67",
    accountHolder: "Ekspress24 Kargo A.Ş.",
    // Anlaşma
    paymentTermDays: 30,
    // Araçlar
    vehicles: [
      {
        id: "v1",
        plate: "34 ABC 001",
        brand: "Mercedes",
        model: "Actros",
        vehicleType: "tir",
        year: 2022,
        capacity: 24,
        status: "on_road",
        currentDriverId: "d1",
        currentDriverName: "Mehmet Demir",
        lastTrip: "İstanbul → Ankara",
        nextInspectionDate: "2024-06-01",
      },
      {
        id: "v2",
        plate: "34 DEF 002",
        brand: "Volvo",
        model: "FH",
        vehicleType: "tir",
        year: 2021,
        capacity: 24,
        status: "idle",
        nextInspectionDate: "2024-08-15",
        isInsuranceExpiringSoon: true,
      },
      {
        id: "v3",
        plate: "34 GHI 003",
        brand: "Ford",
        model: "Transit",
        vehicleType: "van",
        year: 2023,
        capacity: 2,
        status: "maintenance",
        nextInspectionDate: "2025-01-10",
      },
    ],
    // Sürücüler
    drivers: [
      {
        id: "d1",
        fullName: "Mehmet Demir",
        phone: "+90 532 111 2233",
        nationalId: "12345678901",
        licenseClass: "CE",
        licenseExpiry: "2026-03-15",
        hasSrcCertificate: true,
        srcExpiryDate: "2025-09-01",
        status: "on_trip",
        activeVehicleId: "v1",
        activeVehiclePlate: "34 ABC 001",
        totalTrips: 412,
      },
      {
        id: "d2",
        fullName: "Ali Kaya",
        phone: "+90 532 222 3344",
        nationalId: "98765432101",
        licenseClass: "CE",
        licenseExpiry: "2025-11-20",
        hasSrcCertificate: true,
        srcExpiryDate: "2024-02-10", // süresi yakın
        status: "available",
        totalTrips: 287,
      },
    ],
    // Evraklar
    documents: [
      {
        id: "doc1",
        documentType: "vergi_levhasi",
        label: "Vergi Levhası",
        uploadedAt: "2024-01-10",
        expiryDate: "2025-01-10",
        isExpired: false,
        isExpiringSoon: false,
      },
      {
        id: "doc2",
        documentType: "imza_sirkuleri",
        label: "İmza Sirküleri",
        uploadedAt: "2023-06-01",
        isExpired: false,
        isExpiringSoon: false,
      },
      {
        id: "doc3",
        documentType: "tasima_sozlesmesi",
        label: "Taşıma Sözleşmesi",
        uploadedAt: "2024-01-01",
        expiryDate: "2025-01-01",
        isExpired: false,
        isExpiringSoon: true,
      },
    ],
  },
  "2": {
    id: "2",
    name: "Kuzey Lojistik A.Ş.",
    supplierType: "logistics",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Fatma Şahin",
    contactPersonTitle: "Müşteri Direktörü",
    contactPhone: "+90 312 555 0002",
    contactEmail: "fatma.sahin@kuzeylojistik.com",
    city: "Ankara",
    vehicleCount: 8,
    driverCount: 10,
    activeTripsCount: 2,
    totalTripsCount: 634,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2021-03-15",
    updatedAt: "2024-02-01",
    createdBy: "admin",
    taxOffice: "Çankaya V.D.",
    taxNumber: "9876543210",
    officialAddress: "Kızılay Mah. No:5 Çankaya / Ankara",
    iban: "TR98 0001 0017 0000 0009 8765 43",
    accountHolder: "Kuzey Lojistik A.Ş.",
    paymentTermDays: 45,
    pricePerTrip: 2500,
    vehicles: [
      {
        id: "v10",
        plate: "06 XYZ 100",
        brand: "MAN",
        model: "TGX",
        vehicleType: "tir",
        year: 2020,
        capacity: 22,
        status: "on_road",
        lastTrip: "Ankara → İzmir",
        nextInspectionDate: "2024-12-01",
      },
    ],
    drivers: [
      {
        id: "d10",
        fullName: "Hasan Çelik",
        phone: "+90 533 444 5566",
        nationalId: "11122233344",
        licenseClass: "CE",
        licenseExpiry: "2027-05-10",
        hasSrcCertificate: true,
        srcExpiryDate: "2024-03-15", // yakın bitiş
        status: "on_trip",
        activeVehicleId: "v10",
        activeVehiclePlate: "06 XYZ 100",
        totalTrips: 198,
      },
    ],
    documents: [
      {
        id: "doc10",
        documentType: "k_belgesi",
        label: "K Belgesi",
        uploadedAt: "2022-01-01",
        expiryDate: "2024-01-01",
        isExpired: true,
        isExpiringSoon: false,
      },
      {
        id: "doc11",
        documentType: "trafik_sigortasi",
        label: "Trafik Sigortası",
        uploadedAt: "2023-08-01",
        expiryDate: "2024-03-01",
        isExpired: false,
        isExpiringSoon: true,
      },
    ],
  },
  "3": {
    id: "3",
    name: "AKSA Lojistik",
    supplierType: "logistics",
    status: "active",
    contractType: "commission",
    contactPerson: "Kemal Arslan",
    contactPersonTitle: "Genel Müdür",
    contactPhone: "+90 232 555 0003",
    contactEmail: "kemal@aksalojistik.com",
    city: "İzmir",
    vehicleCount: 5,
    driverCount: 6,
    activeTripsCount: 1,
    totalTripsCount: 321,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2022-07-01",
    updatedAt: "2024-01-20",
    createdBy: "admin",
    taxOffice: "Konak V.D.",
    taxNumber: "5554443332",
    officialAddress: "Alsancak Mah. No:22 Konak / İzmir",
    paymentTermDays: 30,
    vehicles: [],
    drivers: [],
    documents: [],
  },
  "4": {
    id: "4",
    name: "Bedirhan Nakliyat",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Bedirhan Yıldız",
    contactPersonTitle: "Sahip",
    contactPhone: "+90 505 666 7788",
    city: "Bursa",
    vehicleCount: 2,
    driverCount: 2,
    activeTripsCount: 1,
    totalTripsCount: 145,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2022-11-01",
    updatedAt: "2024-01-05",
    createdBy: "admin",
    pricePerTrip: 1800,
    paymentTermDays: 15,
    vehicles: [
      {
        id: "v20",
        plate: "16 BDR 001",
        brand: "DAF",
        model: "XF",
        vehicleType: "kamyon",
        year: 2019,
        capacity: 12,
        status: "on_road",
        currentDriverId: "d20",
        currentDriverName: "Bedirhan Yıldız",
        lastTrip: "Bursa → İstanbul",
        nextInspectionDate: "2025-03-01",
      },
    ],
    drivers: [
      {
        id: "d20",
        fullName: "Bedirhan Yıldız",
        phone: "+90 505 666 7788",
        nationalId: "55566677788",
        licenseClass: "C",
        licenseExpiry: "2028-04-20",
        hasSrcCertificate: true,
        srcExpiryDate: "2026-04-20",
        status: "on_trip",
        activeVehicleId: "v20",
        activeVehiclePlate: "16 BDR 001",
        totalTrips: 145,
      },
    ],
    documents: [],
  },
  "5": {
    id: "5",
    name: "Çetin Taşımacılık",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_desi",
    contactPerson: "Cemal Çetin",
    contactPersonTitle: "Sahip",
    contactPhone: "+90 542 777 8899",
    city: "Konya",
    vehicleCount: 1,
    driverCount: 1,
    activeTripsCount: 0,
    totalTripsCount: 89,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2023-02-01",
    updatedAt: "2024-02-10",
    createdBy: "admin",
    pricePerDesi: 3.2,
    paymentTermDays: 7,
    vehicles: [
      {
        id: "v30",
        plate: "42 CML 001",
        brand: "Renault",
        model: "D-Series",
        vehicleType: "kamyon",
        year: 2018,
        capacity: 8,
        status: "idle",
        nextInspectionDate: "2024-02-28",
        isInsuranceExpiringSoon: true,
      },
    ],
    drivers: [
      {
        id: "d30",
        fullName: "Cemal Çetin",
        phone: "+90 542 777 8899",
        nationalId: "33344455566",
        licenseClass: "C",
        licenseExpiry: "2024-05-15",
        hasSrcCertificate: false,
        status: "available",
        totalTrips: 89,
      },
    ],
    documents: [
      {
        id: "doc30",
        documentType: "kasko",
        label: "Kasko",
        uploadedAt: "2023-01-01",
        expiryDate: "2024-01-01",
        isExpired: true,
        isExpiringSoon: false,
      },
    ],
  },
  "6": {
    id: "6",
    name: "Güney Ambar",
    supplierType: "warehouse",
    status: "active",
    contractType: "fixed_salary",
    contactPerson: "Serkan Güneş",
    contactPersonTitle: "Depo Müdürü",
    contactPhone: "+90 322 555 0006",
    contactEmail: "serkan@guneyambar.com",
    city: "Adana",
    vehicleCount: 0,
    driverCount: 0,
    activeTripsCount: 0,
    totalTripsCount: 0,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2023-05-01",
    updatedAt: "2024-01-30",
    createdBy: "admin",
    taxOffice: "Seyhan V.D.",
    taxNumber: "7778889991",
    officialAddress: "Sanayi Mah. Depo Sok. No:15 Seyhan / Adana",
    paymentTermDays: 60,
    vehicles: [],
    drivers: [],
    documents: [
      {
        id: "doc60",
        documentType: "imza_sirkuleri",
        label: "İmza Sirküleri",
        uploadedAt: "2023-05-01",
        isExpired: false,
        isExpiringSoon: false,
      },
    ],
  },
  "7": {
    id: "7",
    name: "Merkez Lojistik",
    supplierType: "logistics",
    status: "passive",
    contractType: "per_trip",
    contactPerson: "Selin Aydın",
    contactPersonTitle: "Yönetici",
    contactPhone: "+90 216 555 0007",
    city: "İstanbul",
    vehicleCount: 3,
    driverCount: 4,
    activeTripsCount: 0,
    totalTripsCount: 256,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2021-08-01",
    updatedAt: "2023-11-01",
    createdBy: "admin",
    pricePerTrip: 2200,
    paymentTermDays: 45,
    vehicles: [],
    drivers: [],
    documents: [],
  },
}
