import type { BranchEntitlementRow, BranchEntitlementSummary } from "../_types"

// TODO: Remove when API is ready
const rows: BranchEntitlementRow[] = [
  {
    branchId: "branch-antalya",
    branchName: "Antalya Şube",
    branchCode: "ANT-001",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.25,
    alimHakedisTotal: 12450,
    dagitimHakedisTotal: 8320,
    toplamHakedis: 20770,
    teslimatiBeklenen: 3150,
    onaylanan: 15200,
    onayBekleyen: 4120,
    iptalEdilen: 1450,
    kargoAdedi: 284,
  },
  {
    branchId: "branch-mersin",
    branchName: "Mersin Şube",
    branchCode: "MRS-002",
    alimHakedisOrani: 0.18,
    dagitimHakedisOrani: 0.22,
    alimHakedisTotal: 9800,
    dagitimHakedisTotal: 6100,
    toplamHakedis: 15900,
    teslimatiBeklenen: 2400,
    onaylanan: 11800,
    onayBekleyen: 2700,
    iptalEdilen: 1400,
    kargoAdedi: 210,
  },
  {
    branchId: "branch-istanbul-avr",
    branchName: "İstanbul Avrupa Şube",
    branchCode: "IST-003",
    alimHakedisOrani: 0.22,
    dagitimHakedisOrani: 0.28,
    alimHakedisTotal: 28500,
    dagitimHakedisTotal: 19200,
    toplamHakedis: 47700,
    teslimatiBeklenen: 7200,
    onaylanan: 35600,
    onayBekleyen: 8900,
    iptalEdilen: 3200,
    kargoAdedi: 562,
  },
  {
    branchId: "branch-istanbul-anadolu",
    branchName: "İstanbul Anadolu Şube",
    branchCode: "IST-004",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.25,
    alimHakedisTotal: 22300,
    dagitimHakedisTotal: 15800,
    toplamHakedis: 38100,
    teslimatiBeklenen: 5400,
    onaylanan: 28400,
    onayBekleyen: 6100,
    iptalEdilen: 3600,
    kargoAdedi: 478,
  },
  {
    branchId: "branch-ankara",
    branchName: "Ankara Şube",
    branchCode: "ANK-005",
    alimHakedisOrani: 0.19,
    dagitimHakedisOrani: 0.24,
    alimHakedisTotal: 18200,
    dagitimHakedisTotal: 12400,
    toplamHakedis: 30600,
    teslimatiBeklenen: 4800,
    onaylanan: 22100,
    onayBekleyen: 5500,
    iptalEdilen: 3000,
    kargoAdedi: 395,
  },
  {
    branchId: "branch-izmir",
    branchName: "İzmir Şube",
    branchCode: "IZM-006",
    alimHakedisOrani: 0.21,
    dagitimHakedisOrani: 0.26,
    alimHakedisTotal: 15600,
    dagitimHakedisTotal: 10200,
    toplamHakedis: 25800,
    teslimatiBeklenen: 3900,
    onaylanan: 18900,
    onayBekleyen: 4200,
    iptalEdilen: 2700,
    kargoAdedi: 330,
  },
  {
    branchId: "branch-bursa",
    branchName: "Bursa Şube",
    branchCode: "BRS-007",
    alimHakedisOrani: 0.17,
    dagitimHakedisOrani: 0.21,
    alimHakedisTotal: 8900,
    dagitimHakedisTotal: 5600,
    toplamHakedis: 14500,
    teslimatiBeklenen: 2100,
    onaylanan: 10800,
    onayBekleyen: 2300,
    iptalEdilen: 1400,
    kargoAdedi: 185,
  },
  {
    branchId: "branch-adana",
    branchName: "Adana Şube",
    branchCode: "ADN-008",
    alimHakedisOrani: 0.18,
    dagitimHakedisOrani: 0.23,
    alimHakedisTotal: 11200,
    dagitimHakedisTotal: 7400,
    toplamHakedis: 18600,
    teslimatiBeklenen: 2800,
    onaylanan: 13600,
    onayBekleyen: 3400,
    iptalEdilen: 1600,
    kargoAdedi: 245,
  },
  {
    branchId: "branch-gaziantep",
    branchName: "Gaziantep Şube",
    branchCode: "GAZ-009",
    alimHakedisOrani: 0.16,
    dagitimHakedisOrani: 0.2,
    alimHakedisTotal: 7200,
    dagitimHakedisTotal: 4800,
    toplamHakedis: 12000,
    teslimatiBeklenen: 1800,
    onaylanan: 8600,
    onayBekleyen: 2100,
    iptalEdilen: 1300,
    kargoAdedi: 158,
  },
  {
    branchId: "branch-konya",
    branchName: "Konya Şube",
    branchCode: "KON-010",
    alimHakedisOrani: 0.15,
    dagitimHakedisOrani: 0.19,
    alimHakedisTotal: 6400,
    dagitimHakedisTotal: 3900,
    toplamHakedis: 10300,
    teslimatiBeklenen: 1500,
    onaylanan: 7500,
    onayBekleyen: 1800,
    iptalEdilen: 1000,
    kargoAdedi: 132,
  },
]

function cloneRow(row: BranchEntitlementRow): BranchEntitlementRow {
  return { ...row }
}

export function getBranchEntitlementRows(): BranchEntitlementRow[] {
  return rows.map(cloneRow).sort((a, b) => b.toplamHakedis - a.toplamHakedis)
}

export function getBranchEntitlementSummary(): BranchEntitlementSummary {
  const totals = rows.reduce(
    (acc, row) => ({
      toplamHakedis: acc.toplamHakedis + row.toplamHakedis,
      alimHakedisTotal: acc.alimHakedisTotal + row.alimHakedisTotal,
      dagitimHakedisTotal: acc.dagitimHakedisTotal + row.dagitimHakedisTotal,
      teslimatiBeklenen: acc.teslimatiBeklenen + row.teslimatiBeklenen,
      onayBekleyen: acc.onayBekleyen + row.onayBekleyen,
    }),
    {
      toplamHakedis: 0,
      alimHakedisTotal: 0,
      dagitimHakedisTotal: 0,
      teslimatiBeklenen: 0,
      onayBekleyen: 0,
    },
  )
  return totals
}
